core/urls.py
from django.urls import path, include

from . import views

app_name = "core"


urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile_view, name="profile"),
    # Retreat
    # path('request-retreat/', views.requestRetreat, name='request_retreat'),

    # Transfer
    path('transfer/', views.makeTransfer, name='make_transfer'),
    path('confirm-transaction/', views.confirmTransaction, name='confirm-transaction'),
    # path('modifier_statut/', views.modifier_statut, name='modifier_statut'),
    path('modifier_statut/<str:transaction_id>/', views.modifier_statut, name='modifier_statut'),
    # path('transfer-detail/', views.getTransfersDetail, name='transfer-detail'),

    # # RECHARGE
    path('recharge/', views.recharge_wallet, name='Recharge'),

    #solde
    path('solde/', views.solde, name='solde'),

    # # HISTORY
    # path('recharge-history/<uuid:id>/', views.getRechargeHistory, name='recharge-history'),    
    # path('transfers-history/<uuid:id>/', views.getTransfersHistory, name='transfers-history'),

    #Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),

    #paypal webhook
    path('paypal-handler/', views.paypal_ipn_handler, name="paypal-handler"),

    #stripe webhook
    path('stripe_webhooks/', views.stripe_webhook, name='stripe_webhooks'),

    # Payment Successful
    path("payment-completed/",  views.payment_completed_view, name="payment-completed"),

    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
    
    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    path("success/", views.success, name="success"),
    path("cancel/", views.cancel, name="cancel"),

    # path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('pending/', views.pending_page, name='pending_page'),
    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
]

possapay_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path("user/",include("userAuth.urls"))
]

userAuth/urls.py
from django.urls import path,include

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
#     TokenBlacklistView
# )

from . import views
# from .views import ChangePasswordView

app_name = "userAuth"

urlpatterns = [
    # User registration Routes
    path('register/', views.register_view, name='register'),
    # User login Routes
    path('login/', views.login_view,name='login'),
    # logout
    path('logout/', views.logout_view,name='logout'),



                  #SERVICES

    #sevices demande
    path('service/demande/', views.service_demand, name='service_demand'),
    
    #sevices Dashboard
    path('service/dashboard/', views.service_dashboard, name='service_dashboard'),

    #create service
    path('service/create/', views.create_service, name='create_service'),

    #update service
    path('service/update/<uuid:service_id>/', views.update_service, name='update_service'),
    
    #delete service
    path('service/delete/<uuid:service_id>/', views.delete_service, name='delete_service'),




    # Update user profile image
    # path('user-images-profile/<uuid:user_id>/', views.userProfileImageUpdate, name='user-image-profile'),

    # Checking user Secret code
    # path('check-secret/', views.check_secret_code),
    path('set-secret/', views.set_secret_code, name='set-secret'),
    # path('set-secret/<str:request_type>/<uuid:user_id>/', views.set_user_secret, name='set_user_secret'),
    
    # #creat service
    #path('service/create/<uuid:user_id>/', views.create_service, name='create_service'),
    #reception des fond
    # path('service/receive/', views.reception, name='reception'),

    # User token refresh Routes
    # path('token/refresh-token/', TokenRefreshView.as_view(),name='refresh_token'),
    
    # path('login/', views.login),
    # User view details
    # path('user-detail/<uuid:id>/', views.userDetail),

    # AUTH for password
    # Changing password
    # path('change-password/<uuid:id>/', ChangePasswordView.as_view(),name='change_password'),
    # Password reset
    # path('password-reset/', include('django_rest_passwordreset.urls'), name='password_reset'),

    # AUTH for Phone Number
    # Setting phone number
    # path('phone-number/<uuid:id>/', views.setPhoneNumber,name='set_phone_number'),
    # # Confirming phone number
    # path('phone-number-confirmation/<uuid:id>/', views.confirmPhoneNumber,name='confirm_phone_number'),

    # AUTH for Email
    # Changing email
    # path('email-change/<uuid:id>/', views.changeEmail, name='changing_email'),
    # # Validating email
    # path('email-verification/<uuid:id>/', views.verifyEmail, name='verify_email'),

    # WALLET
    # Get user Wallet
    # path('user-wallets/<uuid:user_id>/', views.get_wallet, name='user_wallet')
   

]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Api de Paiement</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
    />
  </head>
  <body>
    <!-- Header -->
    <header class="header">
      <a href="{% url 'core:index' %}">
        <img
          src="{% static 'assets/image/logo.png' %}"
          alt=""
          class="possa-logo"
        />
      </a>

      <i class="fa fa-bars toggle-btn"></i>

      <nav class="navbar nav">
        <a href="{% url 'core:index' %}" style="--i: 1">Accueil</a>
        <a href="#" style="--i: 2">
          <div class="dropdown">
            <div class="select">
              <span class="selected">Mon compte</span>
              <div class="caret"></div>
            </div>
            <ul class="menu">
              <li>
                <a href="{% url 'core:make_transfer' %}">Envois</a>
              </li>
              <li><a href="{% url 'core:Recharge' %}">Recharger</a></li>
              <li><a href="{% url 'core:solde' %}">Solde</a></li>
              <li><a href="{% url 'userAuth:service_dashboard' %}">API</a></li>
            </ul>
          </div>
        </a>
        <a href="#" style="--i: 3">A Propos</a>
        <a href="#" style="--i: 4">Services</a>
        <a href="#" style="--i: 5">Contact</a>
      </nav>

      <div class="connect">
        {% if request.user.is_authenticated %}
        <a href="{% url 'userAuth:logout' %}"
          ><button class="button" id="">Se deconnecter</button>
        </a>
        {% else %}
        <a href="{% url 'userAuth:login' %}"
          ><button class="button" id="">Se connecter</button>
        </a>
        {% endif %}
        <i class="fa-solid fa-moon mode"></i>
        <!-- <div class="bg-nav"></div> -->
      </div>
      {% if messages %} {% for message in messages %}
      <div class="header alert alert-{{ message.tags }}" role="alert">
        <strong>Message: {{ message }}</strong>
      </div>
      {% endfor %} {% endif %}
    </header>

    {% block content %} {% endblock content %}
    <script src="{% static 'assets/js/script.js' %}"></script>
  </body>
</html>