core/urls.py
from django.urls import path, include

from . import views

app_name = "core"


urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile_view, name="profile"),
    # Retreat
    # path('request-retreat/', views.requestRetreat, name='request_retreat'),

    # Transfer
    path('transfer/', views.makeTransfer, name='make_transfer'),
    path('confirm-transaction/', views.confirmTransaction, name='confirm-transaction'),
    # path('modifier_statut/', views.modifier_statut, name='modifier_statut'),
    path('modifier_statut/<str:transaction_id>/', views.modifier_statut, name='modifier_statut'),
    # path('transfer-detail/', views.getTransfersDetail, name='transfer-detail'),

    # # RECHARGE
    path('recharge/', views.recharge_wallet, name='Recharge'),

    #solde
    path('solde/', views.solde, name='solde'),

    # # HISTORY
    # path('recharge-history/<uuid:id>/', views.getRechargeHistory, name='recharge-history'),    
    # path('transfers-history/<uuid:id>/', views.getTransfersHistory, name='transfers-history'),

    #Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),

    #paypal webhook
    path('paypal-handler/', views.paypal_ipn_handler, name="paypal-handler"),

    #stripe webhook
    path('stripe_webhooks/', views.stripe_webhook, name='stripe_webhooks'),

    # Payment Successful
    path("payment-completed/",  views.payment_completed_view, name="payment-completed"),

    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
    
    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    path("success/", views.success, name="success"),
    path("cancel/", views.cancel, name="cancel"),

    # path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('pending/', views.pending_page, name='pending_page'),
    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
]

possapay_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path("user/",include("userAuth.urls"))
]

core/views.py
from django.http import JsonResponse
from decimal import Decimal
import math
from django.http import Http404,HttpResponse
from django.dispatch import receiver
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import redirect,render,get_object_or_404

# from rest_framework.decorators import api_view,permission_classes
# from rest_framework.response import Response
# from rest_framework.permissions import IsAuthenticated
# from rest_framework import status
from django.core.exceptions import ObjectDoesNotExist
from userAuth.models import CustomUser,Wallet
from .utils import send_order_notification


from django.contrib.auth.hashers import check_password

from .models import Transfer, RechargeWallet,Retreat,Transaction
# from .serializer import (
#     RechargeWalletSerializer, TransferSerializer, RetreatSerializer
# )
import stripe
from django.conf import settings
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received



#home
def index(request):
    return render(request, 'core/index.html')

#profile
def profile_view(request):
    
    return render(request, 'core/profile.html')


@login_required 
def makeTransfer(request):
    user = request.user
    sender_country = user.country
     # Vérifier le portefeuille de l'expéditeur et recuperer la devise
    
    try:
        sender_wallet = Wallet.objects.get(user_id=user.id)
        devise = sender_wallet.devise
    except Wallet.DoesNotExist:
        messages.error(request, "Vous n'avez pas de portefeuille associé.")
        return redirect('core:make_transfer')
    
    #1er requete envoie d'argent
    if request.method == 'POST':
        email = request.POST.get("recipient_email")
        phone = request.POST.get("phone")
        amount_1 = request.POST.get("montant")
        receiver_type = request.POST.get("receiver_type")

        statut = 'lock' if receiver_type  == 'entreprise' else 'Pending'

        # Vérification des champs obligatoires
        if not all([email, amount_1, devise, receiver_type,]):
            # print('email:',email, amount_1, devise, receiver_type, )
            messages.warning(request, "Tous les champs sont requis.")
            return redirect("core:make_transfer")

        try:
            amount_1 = Decimal(amount_1)
            if amount_1 <= 0:
                raise ValueError("Le montant doit être positif.")
        except (ValueError, TypeError):
            messages.warning(request, "Montant invalide.")
            return redirect("core:make_transfer")
            
        try:
            receiver = CustomUser.objects.get(email=email)
            receiver_country = receiver.country
            receiver_wallet = Wallet.objects.get(
                    user_id=receiver.id,
                )
            to_devise = receiver_wallet.devise

        except CustomUser.DoesNotExist:
            messages.warning(request, f"Il n'existe aucun utilisateur avec l'email : {email}")
            return redirect("core:make_transfer")
            
         # Calcul des frais d'assurance et frais d'envois
        amount_assur = (2 * amount_1) / 100 if receiver_type == "entreprise" else 0
        frais = 0 if sender_country  == receiver_country else (2 * amount_1) / 100
        if devise == 'XAF':
            frais = math.ceil(frais)
            amount_assur = math.ceil(amount_assur)
        elif devise == 'EUR':
            frais = round(frais, 2)
            amount_assur = round(amount_assur,2)
            
        total_amount = amount_1 + amount_assur + frais
        

        if devise == to_devise:
            receiver_amount=amount_1
        elif devise == 'XAF' and to_devise == 'EUR':
            receiver_amount=amount_1 / 655.957
        elif devise == 'EUR' and to_devise == 'XAF':
            receiver_amount=amount_1 * 655.957
        else:
            # Si aucune des conditions ci-dessus n'est remplie, lever une exception
            raise ValueError(f"La conversion entre {devise} et {to_devise} n'est pas définie.")

       

        # Vérifier le mot de passe secret
        # if not check_password(secret_code, user.secret_code):
        #         messages.warning(request, "Mot de passe incorrect.")
        #         return redirect("core:make_transfer")

        # Vérifier le solde disponible
        if sender_wallet.amount < total_amount:
                print('sender_wallet.amount:',sender_wallet.amount,'total_amount', total_amount)

                messages.warning(request, "Vous n'avez pas assez d'argent dans votre compte.")
                return redirect("core:make_transfer")

        request.session['transaction_data'] = {
                'receiver_email': email,
                'receiver_name': receiver.get_full_name(),
                'receiver_phone': receiver.phone_number,
                'amount_1': float(amount_1),
                'receiver_amount': float(receiver_amount),
                'total_amount': float(total_amount),
                'currency': devise,
                'to_devise': to_devise,
                'sender_country':sender_country,
                'receiver_country':receiver_country,
                'receiver_type': receiver_type,
                'amount_assur': float(amount_assur),
                'frais': float(frais),
                'statut':statut
            }
        return redirect("core:confirm-transaction")  
    

    context = {
        "devise": devise,
    }
    return render(request, 'core/transfert.html',context)

#confirme transaction
@login_required
def confirmTransaction(request):
    transaction_data = request.session.get('transaction_data')
    print('transaction_data:',transaction_data)

    if not transaction_data:
            messages.error(request, "Aucune transaction à confirmer.")
            return redirect('core:make_transfer')
    if request.method == 'POST':
        print('transaction_data:',transaction_data)
        user = request.user
        receiver_email = transaction_data['receiver_email']
        receiver_name = transaction_data['receiver_name']
        receiver_phone = transaction_data['receiver_phone']
        amount = Decimal(transaction_data['amount_1'])
        receiver_amount = transaction_data['receiver_amount']
        devise = transaction_data['currency']
        frais = transaction_data['frais']
        total_amount = Decimal(transaction_data['total_amount'])
        receiver_type = transaction_data['receiver_type']
        statut = transaction_data['statut']
        from_country = transaction_data['sender_country']
        to_country = transaction_data['receiver_country']
        amount_assur = transaction_data['amount_assur']
        to_devise = transaction_data['to_devise']
        secret_code = request.POST.get("password")   

        # print('transaction_data:',receiver_email,receiver_type,amount)
        

        if not transaction_data:
            messages.error(request, "Aucune transaction à confirmer.")
            return redirect('core:make_transfer')

        # from_country=user.country      
        statut = transaction_data['statut']
        from_country = transaction_data['receiver_country']
        amount_assur = Decimal(transaction_data['amount_assur'])

        # Vérifier le mot de passe secret
        if not check_password(secret_code, user.secret_code):
                messages.warning(request, "Mot de passe incorrect.")
                return redirect("core:make_transfer")
        
        try:
            receiver = CustomUser.objects.get(email=receiver_email)
            to_country = receiver.country
            receiver_wallet = Wallet.objects.get(
                    user_id=receiver.id,
                )
            to_devise = receiver_wallet.devise
        except CustomUser.DoesNotExist:
            messages.error(request, "Le récepteur n'existe plus.")
            return redirect('core:make_transfer')


        try:
            with transaction.atomic():
                # Vérifier si le récepteur existe
               
                sender_wallet = Wallet.objects.get(user_id=user.id)
                
                # Vérifier le solde de l'expéditeur
                if sender_wallet.amount < total_amount:
                    messages.error(request, "Fonds insuffisants.")
                    return redirect('core:make_transfer')
            
                
                # Compte frais
                
                fees_wallet =Wallet.objects.get(user_id='ce67d2d02dcc407fa049e025be9205fa')
                print('hello',fees_wallet)
                # Effectuer la transaction
                sender_wallet.amount -= total_amount
                sender_wallet.save()

                if frais>0:
                    fees_wallet.amount += Decimal(frais)
                    fees_wallet.save()

                if amount_assur>0:
                    fees_wallet.amount += Decimal(amount_assur)
                    fees_wallet.save()

                if statut == 'lock':
                    fees_wallet.amount += Decimal(receiver_amount)
                    fees_wallet.save()
                else:
                    receiver_wallet.amount += Decimal(receiver_amount)
                    receiver_wallet.save()

                statut = 'completed' if statut == 'pending' else statut

                # Enregistrer la transaction
                Transaction.objects.create(
                    sender=user,
                    receiver=receiver,
                    amount=amount,
                    currency=devise,
                    receiver_type=receiver_type,
                    payment_mode='PossaPay', 
                    amount_assur=amount_assur,
                    from_country=from_country,
                    to_country=to_country,

templates/core/anciens/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>API</title>
    <!-- <link rel="icon" href="{% static 'assets/image/the_sauce.png' %}"> -->
    <!-- font awesome cdn link  -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  </head>
  <body>
    <!-- Section en-tête commence  -->
    <header>
      <div class="header">
        <a href="o" class="logo">
          <img src="{% static 'assets/image/the_sauce.png' %}" alt="Logo" />
        </a>

        <nav class="navbar">
          <ul>
            <li class="deroulant">
              <a href="{% url 'core:index' %}">Accueil</a>
            </li>
            <li class="deroulant">
              <a>Compte</a>
              <ul class="sous">
                <li><a href="{% url 'core:make_transfer' %}">Envois</a></li>
                <li><a href="{% url 'core:Recharge' %}">Recharger</a></li>
                <li><a href="{% url 'core:solde' %}">Solde</a></li>
                <!-- {% for c in categories %}
                <li>
                  <a href="o">{{c.title}}</a>
                </li>
                {% endfor%} -->
                <!-- <hr />
                <li><a href="o">Voir plus</a></li> -->
              </ul>
            </li>
            <li class="deroulant">
              <a href="o">API</a>
            </li>
            <li class="deroulant"><a href="#">Finance</a></li>
          </ul>
        </nav>

        <div class="icons">
          <div class="fas fa-bars" id="menu-btn"></div>
          <div class="fas fa-search" id="search-btn"></div>
          <a href="{% url 'core:profile' %}"
            ><div class="fas fa-user" id="login-btn"></div
          ></a>
        </div>

        <form action="o" method="GET" class="search-form">
          <input
            type="search"
            id="search-box"
            placeholder="rechercher ici..."
            name="q"
          />
          <button class="fas fa-search" type="submit"></button>
          <!-- <label for="search-box" class="fas fa-search"></label> -->
        </form>

        <div class="shopping-cart">
          <a href="o" class="btn"> Panier</a>
          <a href="o" class="btn">passer à la caisse</a>
        </div>
      </div>

      {% if messages %} {% for message in messages %}
      <div class="header alert alert-{{ message.tags }}" role="alert">
        <strong>Message: {{ message }}</strong>
      </div>
      {% endfor %} {% endif %}
    </header>

    <!-- Section en-tête se termine -->
    {% block content %} {% endblock content %}

    <!-- Section pied de page commence  -->

    <section class="footer" di="footer_lien">
      <div class="box-container">
        <div class="box">
          <img src="{% static 'assets/image/the_sauce.png' %}" alt="Logo" />
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cumque
            doloremque voluptates aperiam unde quis voluptatem perspiciatis ipsa
            vel nisi cum repudiandae obcaecati mollitia modi adipisci
          </p>

          <div class="share">
            <a
              href="https://www.facebook.com/the237sauce/"
              class="fab fa-facebook-f"
            ></a>
            <!-- <a href="#" class="fab fa-twitter"></a> -->
            <a
              href="https://www.instagram.com/reme_the_sauce/"
              class="fab fa-instagram"
            ></a>
            <!-- <a href="#" class="fab fa-linkedin"></a> -->
          </div>
        </div>

        <div class="box">
          <h3>contact info</h3>
          <a href="#" class="links">
            <i class="fas fa-phone"></i> (+237) 693 50 81 35
          </a>
          <a href="#" class="links">
            <i class="fas fa-phone"></i> (+237) 656 82 08 99
          </a>
          <a href="#" class="links">
            <i class="fas fa-phone"></i> (+49) 176 75894807
          </a>
          <a href="#" class="links">
            <i class="fas fa-envelope"></i> cabinetfadjeu@gmail.com</a
          >
          <a href="#" class="links">
            <i class="fas fa-map-marker-alt"></i> Düren - Allemagne
          </a>
          <a href="#" class="links">
            <i class="fas fa-map-marker-alt"></i> Yaoundé-Cameroun
          </a>
        </div>

        <div class="box">
          <h3>Liens rapides</h3>
          <a href="o" class="links">
            <i class="fas fa-arrow-right"></i> Accueil
          </a>
          <a href="o" class="links">
            <i class="fas fa-arrow-right"></i> catégories
          </a>
          <a href="o" class="links">
            <i class="fas fa-arrow-right"></i> Produits
          </a>
          <a href="#" class="links">
            <i class="fas fa-arrow-right"></i> Contacts
          </a>
        </div>

        <div class="box">
          <h3>Nos differents modes de payement</h3>
          <!-- <p>Lorem ipsum dolor, sit amet consectetur</p>
       <input type="email" placeholder="your email" class="email">
        <input type="submit" value="subscribe" class="btn">  -->
          <img
            src="{% static 'assets/image/payment.png' %}"
            class="payment-img"
            alt=""
          />
        </div>
      </div>
      <div class="cache">
        <p>realisé par ousmanou.o</p>
      </div>
    </section>

    <!-- Section fin pied de page  -->

    <!-- <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script> -->

    <!-- custom js file link  -->
    <script src="{% static 'assets/js/scriptt.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script src="{% static 'assets/js/function.js' %}"></script>
  </body>
</html>

templates/core/anciens/confirm1.html
{% extends 'partials/base.html' %} {% block content %}
<section class="ho">
  <main class="container">
    <h2>Confirmation de la transaction</h2>
    <p><strong>Nom du Récepteur :</strong> {{ receiver_name }}</p>
    <p><strong>Email du Récepteur :</strong> {{ receiver_email }}*</p>
    <p><strong>Téléphone :</strong> {{ receiver_phone }}</p>
    <p><strong>Montant :</strong> {{ amount_1 }} {{ currency }}**</p>
    <p><strong>Frais :</strong> {{ frais }}*</p>
    <p><strong>Frais :</strong> {{ frais }}*</p>
    <p><strong>Total :</strong> {{ total_amount }} {{ currency }}*</p>
    <p><strong>receiver_type :</strong> {{ receiver_type }}**</p>

    <p>le recepteur recevra {{receiver_amount}}{{to_devise}}</p>
    <p class="note">
      * Les champs marqués d'un astérisque sont obligatoires <br />
    </p>

    <form method="POST" action="{% url 'core:confirm-transaction' %}">
      {% csrf_token %}
      <input type="hidden" name="receiver_name" value="{{ receiver_name }}" />
      <input type="hidden" name="receiver_email" value="{{ receiver_email }}" />
      <input type="hidden" name="receiver_phone" value="{{ receiver_phone }}" />
      <input type="hidden" name="receiver_type" value="{{ receiver_type }}" />
      <input type="hidden" name="amount" value="{{ amount_1 }}" />
      <input type="hidden" name="devise" value="{{ devise }}" />
      <input type="hidden" name="frais" value="{{ frais }}" />
      <input type="hidden" name="total_amount" value="{{ total_amount }}" />
      <input
        type="hidden"
        name="receiver_amount"
        value="{{ receiver_amount }}"
      />
      <input type="hidden" name="to_devise" value="{{ to_devise }}" />
      <div class="input-field">
        <label for="password">Mot de passe</label>
        <input
          type="password"
          name="password"
          id="password"
          placeholder="Mot de passe"
          required
        />
        <div class="underline"></div>
      </div>

      <button type="submit" class="btn-confirm">
        Confirmer la Transaction
      </button>
      <a href="{% url 'core:index' %}" class="btn-cancel">Annuler</a>
    </form>

    <!-- <p><strong>Récepteur :</strong> {{ receiver_name }}</p>
    <p><strong>Email :</strong> {{ email }}</p>
    <p><strong>Téléphone :</strong> {{ receiver_phone }}</p>
    <p><strong>Montant :</strong> {{ amount }} {{ currency }}</p>
    <p><strong>Type de récepteur :</strong> {{ receiver_type }}</p>
    <p><strong>Frais d'assurance :</strong> {{ amount_assur }}</p>
    <p><strong>Frais d'assurance :</strong>{{ frais }}</p> -->

    <!-- <form method="post" action="">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">Confirmer</button>
      <a href="{% url 'core:make_transfer' %}" class="btn btn-danger"
        >Annuler</a
      >
    </form> -->
  </main>
</section>
{% endblock %}

templates/core/anciens/index1.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<!-- Section accueil commence  -->

<section class="home" id="home">
  <div class="content">
    <h3>produits frais et <span>bio</span> pour vous</h3>
    <p>
      Commandez dès Aujourd'hui et Embarquez pour un Voyage Culinaire
      Inoubliable.
    </p>
    <a href="#" class="btn">acheter maintenant</a>
  </div>
</section>

{% endblock content %}

templates/core/anciens/sign-in1.html
{% extends  'partials/base.html' %}
{% load static %}
{% block content %}
<section class="ho">
<main class="container">

    <h2> Se connecter  </h2>
    <form method="post" action="">
        {% csrf_token %}
        <div class="input-field">
            <input type="email" name="email" id="email" placeholder="Email">
            <div class="underline"></div>
        </div>

        <div class="input-field">
            <input type="password" name="password" id="password" placeholder="Mot de passe">
            <div class="underline"></div>
        </div>

        <div class="pass_ouble">
            <a href="/password_reset/">mot de passe oublé</a>
          </div>

        <button type="submit" class="form_input" name="login">Se connecter</button>

        <div class="pass_ouble">
            <p>Vous n'avez pas de compte ?<a href="/user/sign-up/">Créer un compte</a></p>
        </div>

    </form>

</main>
</section>
{% endblock content %}

templates/core/anciens/sign-up1.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css"
/>

<section class="ho">
  <main class="container">
    {% if form.errors %}
    <div class="alert-danger">
      <strong>{{form.errors}}</strong>
    </div>
    {% endif %}
    <h2>S'inscrire</h2>
    <form method="post" action="">
      {% csrf_token %}
      <div class="input-field">
        {{form.username}}
        <div class="underline"></div>
      </div>
      <div class="input-field">
        {{form.email}}
        <div class="underline"></div>
      </div>
      <!-- <div class="input-field">
        {{form.phone_number}}
        <div class="underline"></div>
      </div> -->
      <div class="input-field">
        {{form.password1}}
        <div class="underline"></div>
      </div>
      <div class="input-field">
        {{form.password2}}
        <div class="underline"></div>
      </div>

      <div class="input-field">
        <input
          class="telephone"
          type="tel"
          id="phone"
          name="phone_number"
          required
        />
        <input id="pays" name="country" type="hidden" />
        <input id="code" name="code" type="hidden" />
        <div class="underline"></div>
        <span id="valid-msg" class="hidden">✓ Valid</span>
        <span id="error-msg" class="hidden"></span>
      </div>

      <!-- <input type="submit" value="Continue"> -->
      <button type="submit" class="form_input" name="login">
        Submit &amp; Register
      </button>
    </form>
  </main>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
<script>
  const button = document.querySelector("#check");
  const errorMsg = document.querySelector("#error-msg");
  const validMsg = document.querySelector("#valid-msg");
  var input = document.querySelector("#phone");
  const paysInput = document.querySelector("#pays");
  const codeInput = document.querySelector("#code");
  const fraisInput = document.querySelector("#fraiss");
  const entrees = document.querySelector("#inputs");
  const inforr = document.querySelector("#infor");

  var iti = window.intlTelInput(input, {
    allowDropdown: true,
    autoHideDialCode: false,
    autoPlaceholder: "polite",
    strictMode: true,
    // dropdownContainer: document.body,
    formatOnDisplay: false,
    geoIpLookup: function (callback) {
      fetch("https://ipinfo.io/json")
        .then((response) => response.json())
        .then((data) => callback(data.country))
        .catch(() => callback("us"));
    },
    initialCountry: "auto",
    nationalMode: true,
    placeholderNumberType: "MOBILE",
    preferredCountries: ["de", "fr", "cm", "us", "gb"],
    separateDialCode: true,
    utilsScript: "{% static 'assets/js/input/utils.js' %}",
  });

  const errorMap = [
    "Invalid number",
    "Invalid country code",
    "Too short",
    "Too long",
    "Invalid number",
  ];
  const reset = () => {
    input.classList.remove("error");
    errorMsg.innerHTML = "";
    errorMsg.classList.add("hidden");
    validMsg.classList.add("hidden");
  };

  (function updateCountryInfo() {
    const pay = iti.getSelectedCountryData().iso2;
    const code = iti.getSelectedCountryData().dialCode;
    paysInput.value = pay;
    codeInput.value = code;
  })();

  input.addEventListener("countrychange", () => {
    const pay = iti.getSelectedCountryData().iso2;
    const code = iti.getSelectedCountryData().dialCode;
    paysInput.value = pay;
    codeInput.value = code;
    console.log("pay:", pay, "code:", code);
  });

  const showError = (msg) => {
    input.classList.add("error");
    errorMsg.innerHTML = msg;
    errorMsg.classList.remove("hidden");
  };

  // on keyup / change flag: reset
  input.addEventListener("change", reset);
  input.addEventListener("keyup", reset);
</script>

{% endblock content %}