core/urls.py
from django.urls import path, include

from . import views

app_name = "core"


urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile_view, name="profile"),
    # Retreat
    # path('request-retreat/', views.requestRetreat, name='request_retreat'),

    # Transfer
    path('transfer/', views.makeTransfer, name='make_transfer'),
    path('confirm-transaction/', views.confirmTransaction, name='confirm-transaction'),
    # path('modifier_statut/', views.modifier_statut, name='modifier_statut'),
    path('modifier_statut/<str:transaction_id>/', views.modifier_statut, name='modifier_statut'),
    # path('transfer-detail/', views.getTransfersDetail, name='transfer-detail'),

    # # RECHARGE
    path('recharge/', views.recharge_wallet, name='Recharge'),

    #solde
    path('solde/', views.solde, name='solde'),

    # # HISTORY
    # path('recharge-history/<uuid:id>/', views.getRechargeHistory, name='recharge-history'),    
    # path('transfers-history/<uuid:id>/', views.getTransfersHistory, name='transfers-history'),

    #Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),

    #paypal webhook
    path('paypal-handler/', views.paypal_ipn_handler, name="paypal-handler"),

    #stripe webhook
    path('stripe_webhooks/', views.stripe_webhook, name='stripe_webhooks'),

    # Payment Successful
    path("payment-completed/",  views.payment_completed_view, name="payment-completed"),

    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
    
    # Payment Failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    path("success/", views.success, name="success"),
    path("cancel/", views.cancel, name="cancel"),

    # path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('pending/', views.pending_page, name='pending_page'),
    path('api/check-payment/', views.check_payment_status, name='check_payment_status'),
]

possapay_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path("user/",include("userAuth.urls"))
]

userAuth/urls.py
from django.urls import path,include

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
#     TokenBlacklistView
# )

from . import views
# from .views import ChangePasswordView

app_name = "userAuth"

urlpatterns = [
    # User registration Routes
    path('register/', views.register_view, name='register'),
    # User login Routes
    path('login/', views.login_view,name='login'),
    # logout
    path('logout/', views.logout_view,name='logout'),



                  #SERVICES

    #sevices demande
    path('service/demande/', views.service_demand, name='service_demand'),
    
    #sevices Dashboard
    path('service/dashboard/', views.service_dashboard, name='service_dashboard'),

    #create service
    path('service/create/', views.create_service, name='create_service'),

    #update service
    path('service/update/<uuid:service_id>/', views.update_service, name='update_service'),
    
    #delete service
    path('service/delete/<uuid:service_id>/', views.delete_service, name='delete_service'),




    # Update user profile image
    # path('user-images-profile/<uuid:user_id>/', views.userProfileImageUpdate, name='user-image-profile'),

    # Checking user Secret code
    # path('check-secret/', views.check_secret_code),
    path('set-secret/', views.set_secret_code, name='set-secret'),
    # path('set-secret/<str:request_type>/<uuid:user_id>/', views.set_user_secret, name='set_user_secret'),
    
    # #creat service
    #path('service/create/<uuid:user_id>/', views.create_service, name='create_service'),
    #reception des fond
    # path('service/receive/', views.reception, name='reception'),

    # User token refresh Routes
    # path('token/refresh-token/', TokenRefreshView.as_view(),name='refresh_token'),
    
    # path('login/', views.login),
    # User view details
    # path('user-detail/<uuid:id>/', views.userDetail),

    # AUTH for password
    # Changing password
    # path('change-password/<uuid:id>/', ChangePasswordView.as_view(),name='change_password'),
    # Password reset
    # path('password-reset/', include('django_rest_passwordreset.urls'), name='password_reset'),

    # AUTH for Phone Number
    # Setting phone number
    # path('phone-number/<uuid:id>/', views.setPhoneNumber,name='set_phone_number'),
    # # Confirming phone number
    # path('phone-number-confirmation/<uuid:id>/', views.confirmPhoneNumber,name='confirm_phone_number'),

    # AUTH for Email
    # Changing email
    # path('email-change/<uuid:id>/', views.changeEmail, name='changing_email'),
    # # Validating email
    # path('email-verification/<uuid:id>/', views.verifyEmail, name='verify_email'),

    # WALLET
    # Get user Wallet
    # path('user-wallets/<uuid:user_id>/', views.get_wallet, name='user_wallet')
   

]

core/views.py
from django.http import JsonResponse
from decimal import Decimal
import math
from django.http import Http404,HttpResponse
from django.dispatch import receiver
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import redirect,render,get_object_or_404

# from rest_framework.decorators import api_view,permission_classes
# from rest_framework.response import Response
# from rest_framework.permissions import IsAuthenticated
# from rest_framework import status
from django.core.exceptions import ObjectDoesNotExist
from userAuth.models import CustomUser,Wallet
from .utils import send_order_notification


from django.contrib.auth.hashers import check_password

from .models import Transfer, RechargeWallet,Retreat,Transaction
# from .serializer import (
#     RechargeWalletSerializer, TransferSerializer, RetreatSerializer
# )
import stripe
from django.conf import settings
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received



#home
def index(request):
    return render(request, 'core/index.html')

#profile
def profile_view(request):
    
    return render(request, 'core/profile.html')


@login_required 
def makeTransfer(request):
    user = request.user
    sender_country = user.country
     # Vérifier le portefeuille de l'expéditeur et recuperer la devise
    
    try:
        sender_wallet = Wallet.objects.get(user_id=user.id)
        devise = sender_wallet.devise
    except Wallet.DoesNotExist:
        messages.error(request, "Vous n'avez pas de portefeuille associé.")
        return redirect('core:make_transfer')
    
    #1er requete envoie d'argent
    if request.method == 'POST':
        email = request.POST.get("recipient_email")
        phone = request.POST.get("phone")
        amount_1 = request.POST.get("montant")
        receiver_type = request.POST.get("receiver_type")

        statut = 'lock' if receiver_type  == 'entreprise' else 'Pending'

        # Vérification des champs obligatoires
        if not all([email, amount_1, devise, receiver_type,]):
            # print('email:',email, amount_1, devise, receiver_type, )
            messages.warning(request, "Tous les champs sont requis.")
            return redirect("core:make_transfer")

        try:
            amount_1 = Decimal(amount_1)
            if amount_1 <= 0:
                raise ValueError("Le montant doit être positif.")
        except (ValueError, TypeError):
            messages.warning(request, "Montant invalide.")
            return redirect("core:make_transfer")
            
        try:
            receiver = CustomUser.objects.get(email=email)
            receiver_country = receiver.country
            receiver_wallet = Wallet.objects.get(
                    user_id=receiver.id,
                )
            to_devise = receiver_wallet.devise

        except CustomUser.DoesNotExist:
            messages.warning(request, f"Il n'existe aucun utilisateur avec l'email : {email}")
            return redirect("core:make_transfer")
            
         # Calcul des frais d'assurance et frais d'envois
        amount_assur = (2 * amount_1) / 100 if receiver_type == "entreprise" else 0
        frais = 0 if sender_country  == receiver_country else (2 * amount_1) / 100
        if devise == 'XAF':
            frais = math.ceil(frais)
            amount_assur = math.ceil(amount_assur)
        elif devise == 'EUR':
            frais = round(frais, 2)
            amount_assur = round(amount_assur,2)
            
        total_amount = amount_1 + amount_assur + frais
        

        if devise == to_devise:
            receiver_amount=amount_1
        elif devise == 'XAF' and to_devise == 'EUR':
            receiver_amount=amount_1 / 655.957
        elif devise == 'EUR' and to_devise == 'XAF':
            receiver_amount=amount_1 * 655.957
        else:
            # Si aucune des conditions ci-dessus n'est remplie, lever une exception
            raise ValueError(f"La conversion entre {devise} et {to_devise} n'est pas définie.")

       

        # Vérifier le mot de passe secret
        # if not check_password(secret_code, user.secret_code):
        #         messages.warning(request, "Mot de passe incorrect.")
        #         return redirect("core:make_transfer")

        # Vérifier le solde disponible
        if sender_wallet.amount < total_amount:
                print('sender_wallet.amount:',sender_wallet.amount,'total_amount', total_amount)

                messages.warning(request, "Vous n'avez pas assez d'argent dans votre compte.")
                return redirect("core:make_transfer")

        request.session['transaction_data'] = {
                'receiver_email': email,
                'receiver_name': receiver.get_full_name(),
                'receiver_phone': receiver.phone_number,
                'amount_1': float(amount_1),
                'receiver_amount': float(receiver_amount),
                'total_amount': float(total_amount),
                'currency': devise,
                'to_devise': to_devise,
                'sender_country':sender_country,
                'receiver_country':receiver_country,
                'receiver_type': receiver_type,
                'amount_assur': float(amount_assur),
                'frais': float(frais),
                'statut':statut
            }
        return redirect("core:confirm-transaction")  
    

    context = {
        "devise": devise,
    }
    return render(request, 'core/transfert.html',context)

#confirme transaction
@login_required
def confirmTransaction(request):
    transaction_data = request.session.get('transaction_data')
    print('transaction_data:',transaction_data)

    if not transaction_data:
            messages.error(request, "Aucune transaction à confirmer.")
            return redirect('core:make_transfer')
    if request.method == 'POST':
        print('transaction_data:',transaction_data)
        user = request.user
        receiver_email = transaction_data['receiver_email']
        receiver_name = transaction_data['receiver_name']
        receiver_phone = transaction_data['receiver_phone']
        amount = Decimal(transaction_data['amount_1'])
        receiver_amount = transaction_data['receiver_amount']
        devise = transaction_data['currency']
        frais = transaction_data['frais']
        total_amount = Decimal(transaction_data['total_amount'])
        receiver_type = transaction_data['receiver_type']
        statut = transaction_data['statut']
        from_country = transaction_data['sender_country']
        to_country = transaction_data['receiver_country']
        amount_assur = transaction_data['amount_assur']
        to_devise = transaction_data['to_devise']
        secret_code = request.POST.get("password")   

        # print('transaction_data:',receiver_email,receiver_type,amount)
        

        if not transaction_data:
            messages.error(request, "Aucune transaction à confirmer.")
            return redirect('core:make_transfer')

        # from_country=user.country      
        statut = transaction_data['statut']
        from_country = transaction_data['receiver_country']
        amount_assur = Decimal(transaction_data['amount_assur'])

        # Vérifier le mot de passe secret
        if not check_password(secret_code, user.secret_code):
                messages.warning(request, "Mot de passe incorrect.")
                return redirect("core:make_transfer")
        
        try:
            receiver = CustomUser.objects.get(email=receiver_email)
            to_country = receiver.country
            receiver_wallet = Wallet.objects.get(
                    user_id=receiver.id,
                )
            to_devise = receiver_wallet.devise
        except CustomUser.DoesNotExist:
            messages.error(request, "Le récepteur n'existe plus.")
            return redirect('core:make_transfer')


        try:
            with transaction.atomic():
                # Vérifier si le récepteur existe
               
                sender_wallet = Wallet.objects.get(user_id=user.id)
                
                # Vérifier le solde de l'expéditeur
                if sender_wallet.amount < total_amount:
                    messages.error(request, "Fonds insuffisants.")
                    return redirect('core:make_transfer')
            
                
                # Compte frais
                
                fees_wallet =Wallet.objects.get(user_id='ce67d2d02dcc407fa049e025be9205fa')
                print('hello',fees_wallet)
                # Effectuer la transaction
                sender_wallet.amount -= total_amount
                sender_wallet.save()

                if frais>0:
                    fees_wallet.amount += Decimal(frais)
                    fees_wallet.save()

                if amount_assur>0:
                    fees_wallet.amount += Decimal(amount_assur)
                    fees_wallet.save()

                if statut == 'lock':
                    fees_wallet.amount += Decimal(receiver_amount)
                    fees_wallet.save()
                else:
                    receiver_wallet.amount += Decimal(receiver_amount)
                    receiver_wallet.save()

                statut = 'completed' if statut == 'pending' else statut

                # Enregistrer la transaction
                Transaction.objects.create(
                    sender=user,
                    receiver=receiver,
                    amount=amount,
                    currency=devise,
                    receiver_type=receiver_type,
                    payment_mode='PossaPay', 
                    amount_assur=amount_assur,
                    from_country=from_country,
                    to_country=to_country,

templates/core/Recharge.html
{% extends 'partials/base.html' %} {% block content %}

<div class="form-envois">
  <div class="barre"></div>
  <br />
  <form method="post" action="">
    {% csrf_token %}
    <h2>Recharger Mon compte</h2>

    <div class="form2">
      <label for="baseAmount"
        >Montant à envoyer : <span class="star">*</span></label
      >
      <input
        type="number"
        id="baseAmount"
        name="montant"
        required
        placeholder="Entrez le montant"
        step="0.01"
        class="inputEnvois"
      />
      <br /><br />

      <label for="currency">Dévise</label>
      <select id="currency" disabled="disabled" name="currency" class="Envois">
        <option value="{{devise}}">{{ devise }}</option>
      </select>
      <br />

      <label for="payment_mode"
        >Mode de payment<span class="star">*</span></label
      >
      <select id="payment_mode" name="payment_mode" class="Envois">
        <option value="">-- Sélectionnez une option --</option>
        <option value="PayPal">PayPal</option>
        <option value="Visa">Visa</option>
      </select>
      <br />
    </div>

    <div class="buttonEnvois">
      <button type="submit" class="button" name="submit">
        Envoyer
        <!-- </a> -->
      </button>
    </div>
  </form>
</div>

{% endblock content %}

templates/core/cancel.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Cancel</h1>
  </body>
</html>

templates/core/checkout.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<div class="form-envois">
  <div class="barre"></div>
  <br />
  <form method="" action="">
    <h2>Formulaire d'envois d'argent</h2>

    <!-- <div>{{paypal_payment_button.render}}</div> -->
  </form>
  <div>{{paypal_payment_button.render}}</div>
</div>

{% endblock content %}

templates/core/confirm.html
{% extends 'partials/base.html' %} {% block content %}
<div class="form-envois">
  <div class="barre"></div>
  <br />
  <form method="post" action="">
    {% csrf_token %}

    <h2>Confirmation d'envoi</h2>
    <p class="confirmt">
      Monsieur / Madame {{ user.get_full_name }},{{request.user.username|title}}
      vous êtes sur le point d'envoyer de l'argent à une personne ayant les
      informations suivantes :
    </p>

    <div class="form1">
      <p class="para">Nom du bénéficiaire : {{ transaction.receiver_name }}</p>
      <br /><br />
      <p class="para">Email du bénéficiaire : {{transaction.receiver_email}}</p>
      <br /><br />
      <p class="para">
        Montant envoyé : {{ transaction.amount_1 }}{{transaction.currency }}
      </p>
      <br /><br />
      <p class="para">
        Montant recue : {{ transaction.receiver_amount}}
        {{transaction.to_devise}}
      </p>

      <br /><br />
      <p class="para">
        Frais :{{ transaction.frais }} {{ transaction.currency }}
      </p>
      <br /><br />
      <p class="para">
        Assurance :{{ transaction.amount_assur }} {{ transaction.currency }}
      </p>
      <br /><br />
      <p class="para">
        Total a payer : {{ transaction.total_amount }}{{transaction.currency }}
      </p>
      <br /><br />
    </div>

    <div class="form2">
      <div class="form-group">
        <label for="password">Mot de passe :</label>
        <input
          type="password"
          name="password"
          id="password"
          class="input-field"
          required
        />
      </div>

      <div class="buttonEnvois">
        <input type="submit" value="Confirmer" />
      </div>
    </div>
  </form>
</div>
{% endblock content %}

templates/core/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Home</h1>
    <h1>Homepage</h1>
    <form method="POST" action="{% url 'core:Recharge' %}">
      {% csrf_token %}
      <label for="montant">Montant :</label>
      <input
        type="number"
        id="montant"
        name="montant"
        step="0.01"
        min="0"
        required
      />

      <label for="payment_mode">Mode de paiement :</label>
      <select id="payment_mode" name="payment_mode" required>
        <option value="stripe">Stripe</option>
        <option value="paypal">PayPal</option>
      </select>

      <button type="submit">Recharger</button>
    </form>
  </body>
</html>

templates/core/index.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<!-- Home -->
<section class="home">
  <div class="content">
    <h3>Simplifiez vos transactions financières avec <span>PossaPay</span></h3>
    <p>
      <span style="font-weight: bolder"
        >envoyez, recevez et gérez votre argent en toute sécurité, partout et à
        tout moment.
      </span>
    </p>
    <a href="#" class="btn"><span></span>Commencer</a>
    <div class="sci">
      <a href="#" style="--i: 14"><i class="fa-brands fa-facebook-f"></i></a>
      <a href="#" style="--i: 15"><i class="fa-brands fa-twitter"></i></a>
      <a href="#" style="--i: 16"><i class="fa-brands fa-instagram"></i></a>
    </div>
  </div>

  <div class="image">
    <img
      src="{% static 'assets/image/paiem1.JPG' %}"
      alt=""
      class="logo-silhouette"
    />
    <img src="{% static 'assets/image/paiem1.JPG' %}" alt="" class="moon1" />
  </div>
</section>

<!-- Script-->
{% endblock content %}

templates/core/pending.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Traitement en cours...</title>
    <script>
      const sessionId = new URLSearchParams(window.location.search).get(
        "session_id"
      );

      async function checkPaymentStatus() {
        const response = await fetch(
          `/api/check-payment?session_id=${sessionId}`
        );
        const data = await response.json();

        if (data.status === "Completed") {
          window.location.href = "/success"; // Redirection vers la page de succès
        } else if (data.status === "not_found") {
          document.getElementById("status").innerText = "Paiement introuvable.";
        } else {
          setTimeout(checkPaymentStatus, 3000); // Vérifier toutes les 3 secondes
        }
      }

      checkPaymentStatus();
    </script>
  </head>
  <body>
    <h1>Votre paiement est en cours de traitement...</h1>
    <p id="status">Merci de patienter pendant la validation.</p>
  </body>
</html>

templates/core/profile.html
{% extends  'partials/base.html' %}
{% load static %}
{% block content %}

<h1 class="heading ho"> <span> profile</span> </h1>
<section class="profile flex">
    
<div class="mode">
    <h1>{{request.user|title}}</h1>
    <nav class="navbar">
        <ul>
            <li><button class="payment-btn red" id="cash-btn" onclick="selectPayment('cash')">Commandes</button></li>
            <li><button class="payment-btn" id="card-btn" onclick="selectPayment('card')">Address </button></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'userAuth:logout' %}"><button>Se deconnecter</button></a></li>
            {% else %}
                <li><a href="{% url 'userAuth:login' %}"><button>Se connecter</button></a></li>
                <li><a href="{% url 'userAuth:register' %}"><button>S'inscrire</button></a></li>
            {% endif %}
    </nav>
</div>

<section class="commandes payment-info" id="cash-info">
    {% if orders_list %}
        <div class="shopping-cart1">
        <table>
          <thead>
              <tr>
                  <th ><h3>Commandes</h3></th>
                  <th><h3>Date</h3> </th>
                  <th><h3>Status</h3> </th>
                  <th><h3>paiement</h3> </th>
                  <th><h3>Montant</h3></th>
                  <th><h3>Action</h3></th>
                  <th><h3>facture</h3></th>
              </tr>
          </thead>
          <tbody>
             {% for o in page_obj %}
              <tr class="produit">
                  <td><h3>{{ o.id }}</h3></td>
                  <td><h3>{{ o.order_date }}</h3></td>
                  <td><h3>{{ o.product_status |title }}</h3></td>
                  {% if o.paid_status == True %}
                    <td><i class="fas fa-check-circle text-success"></i></td>
                  {% else %}
                    <td><i class="fas fa-times-circle text-danger"></i></td>
                  {% endif%}
                  <td><span class="price"> {{o.price}} €</span></td>
                  <td><h3> <a href="{% url 'core:order-detail' o.id %}">Details</a></h3></td>
                  <td><h3> <a href="{% url 'core:facture' o.id %}">facture</a></h3></td>

                  {% endfor %} 
            
              </tr> 
          </tbody>
      </table>
        <span>
        {% if page_obj.has_previous %}
            
            <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
        {% endif %}
    
        <span>
            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.

        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">suivante</a>
            
        {% endif %}
        </span>
      </div>
    {% else %}
        <div class="credit">Vous n'avez aucune commande.</div>

    {% endif %}
  
</section>
<section class="commandes payment-info hidden" id="card-info">
    <div>
        <h2>Ajouter une adresse</h2>
        <form action="" method="post">{% csrf_token %}
            <div class="flex">
            <td><input type="number" name="mobile" placeholder="Mobile Number" required></td>
            <td><input type="text" name="address" placeholder="Address" required></td>
            </div>
            <td><button type="submit" class="btn" style="background: none;"><h3>Ajouter l'addrese</h3></button></td>
            </form>
    </div>
    {% if address %}
        <div class="shopping-cart1">
            
        <table>
          <thead>
              <tr>
                  <th><h3>id</h3></th>
                  <th ><h3>Telephone</h3></th>
                  <th><h3>Adresse</h3> </th>
                  <th><h3>Adresse par Defaut</h3> </th>
                  <th><h3>Action</h3></th> 
              </tr>
          </thead>
          <tbody>  
             {% for a in address %}
              <tr class="produit">
                  <td><h3>{{ a.id }}</h3></td>
                  <td><h3>{{ a.mobile }}</h3></td>
                  <td><h3>{{ a.address }}</h3></td>
                  {% if a.status == True %}
                    <td><i data-address-id="{{ a.id }}" class="fas fa-check-circle text-success check{{ a.id }} check"></i></td>
                    <td><button data-address-id="{{ a.id }}"  style="display: none;" class="btn make-default-address button{{ a.id }} action_btn">Make Default</button></td>
                    
                  {% else %}
                  <td><i data-address-id="{{ a.id }}" style="display: none;" class="fa fa-check-circle text-success check check{{ a.id }}"></i></td>
                  <td><button data-address-id="{{ a.id }}"   class="btn make-default-address button{{ a.id }} action_btn">Defaut</button></td>
                
                  {% endif%}
              </tr> 
             {% endfor %} 
              
          </tbody>
      </table>
        <span>
        {% if address.has_previous %}
            
            <a href="?page={{ address.previous_page_number }}">précédente</a>
        {% endif %}
    
        <span>
            Page {{ address.number }} sur {{ address.paginator.num_pages }}.

        </span>
        {% if address.has_next %}
            <a href="?page={{ address.next_page_number }}">suivante</a>
            
        {% endif %}
        </span>
      </div>
    {% else %}
        <div class="credit">Vous n'avez aucune Addresse.</div>

    {% endif %}
  
</section>
</section>
{% endblock content %}

templates/core/solde.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<!-- Section accueil commence  -->

<section class="home" id="home">
  <h1>Solde de l'utilisateur</h1>
  <p>Montant: {{ amount }} {{ devise }}</p>

  <h2>Transactions</h2>
  <table>
    <thead>
      <tr>
        <th>Récepteur</th>
        <th>Montant</th>
        <th>Date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{ transaction.receiver.username }}</td>
        <td>{{ transaction.amount }}</td>
        <td>{{ transaction.date_created }}</td>
        <td>{{ transaction.status }}</td>
        <td>
          <a href="{% url 'core:modifier_statut' transaction.id %}"
            >Modifier Statut</a
          >
          {% endfor %}
        </td>
      </tr>
    </tbody>
  </table>
</section>

{% endblock content %}

templates/core/statut_modifier.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}
<!-- Section accueil commence  -->

<section class="home" id="home">
  <div class="content">
    <h1>etes vous sure de vouloire valider votre transaction?</h1>
    <div>
      <!-- <p>etes vous sure de vouloire valider votre transaction?</p> -->
      <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="transaction_id" value="{{ transaction.id }}" />
        <input type="submit" value="ok" />
    </div>
</section>

{% endblock content %}

templates/core/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>success.html</h1>
  </body>
</html>

templates/core/transfert.html
{% extends 'partials/base.html' %} {% load static %} {% block content %}

<!-- Home -->

<div class="form-envois">
  <div class="barre"></div>
  <br />
  <form method="post" action="">
    {% csrf_token %}
    <h2>Formulaire d'envois d'argent</h2>
    <div class="form1">
      <!-- <label for="nomComplet"
        >Nom Complet du bénéficiaire <span class="star">*</span></label
      ><br />
      <input
        type="text"
        id="nomComplet"
        placeholder="Entrer votre nom complet"
        class="inputEnvois"
      />
      <br /><br /> -->

      <label for="recipient_email"
        >Email du bénéficiaire : <span class="star">*</span></label
      >
      <input
        type="email"
        id="recipient_email"
        name="recipient_email"
        class="inputEnvois"
        placeholder="Email du bénéficiaire"
      /><br /><br />

      <label for="tel">Téléphone bénéficiaire <span class="star">*</span></label
      ><br />
      <input
        type="tel"
        id="tel"
        name="phone"
        placeholder="Phone"
        class="inputEnvois"
      />
      <br /><br />
    </div>
    <div class="form2">
      <label for="baseAmount"
        >Montant à envoyer (Fcfa) : <span class="star">*</span></label
      >
      <input
        type="number"
        id="baseAmount"
        name="montant"
        required
        placeholder="Entrez le montant"
        step="0.01"
        class="inputEnvois"
      />
      <br /><br />

      <label for="currency">Dévise </label>
      <select id="currency" disabled="disabled" name="currency" class="Envois">
        <option value="cfa">{{ devise }}</option>
      </select>
      <br /><br />

      <label for="selection"
        >Type de bénéficiaire : <span class="star">*</span></label
      >
      <select id="receiver_type" name="receiver_type" class="">
        <option value="">-- Sélectionnez une option --</option>
        <option value="famille">Famille</option>
        <option value="entreprise">Entreprise</option>
      </select>
    </div>

    <!-- <div class="total">
      Montant total à payer : <span id="totalAmount">0</span> Fcfa
    </div> -->

    <div class="buttonEnvois">
      <button type="submit" class="button" name="submit">Envoyer</button>
    </div>
  </form>
</div>

<!-- Script-->
<script src="{% static 'assets/js/scriptLog.js' %}"></script>

{% endblock content %}